sudo: required

language: elixir

elixir:
  - 1.0.5

otp_release:
  - 17.4
  - 18.0

env:
  matrix:
    - CXX=clang++
    - CXX=g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - boost-latest
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - libboost1.55-all-dev

before_install:
    - mix local.hex --force

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
