sudo: false

language: elixir

elixir:
  - 1.0.5

otp_release:
  - 17.4
  - 18.0

env:
  matrix:
    - CXX=clang++
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang
      - libboost-all-dev
